//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QtekBilisim_Muhasebe.PL.Windows.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QtekBilisim_Muhasebe.PL.Windows.LanguageResources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir veya Birden Fazla Hata Oluşmuştur.
        /// </summary>
        internal static string AggregateException {
            get {
                return ResourceManager.GetString("AggregateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değer Boş Olamaz.
        /// </summary>
        internal static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri Tabanı Tasarımıyla İlgili Bir Hata Meydana Gelmiştir. Bu Hatanın Nedeni Genellikle Karakter Sınırlaması ya da Boş Geçilemez Bir Alan ile İlgilidir..
        /// </summary>
        internal static string DbEntityValidationException {
            get {
                return ResourceManager.GetString("DbEntityValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasör Bulunamadı.
        /// </summary>
        internal static string DirectoryNotFoundException {
            get {
                return ResourceManager.GetString("DirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Bulunamadı.
        /// </summary>
        internal static string FileNotFoundException {
            get {
                return ResourceManager.GetString("FileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri Tipleriyle ile İlgili Format Hatası Yapılmıştır.
        /// </summary>
        internal static string FormatException {
            get {
                return ResourceManager.GetString("FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme İşlemi Başarılı Olmuştur.
        /// </summary>
        internal static string GuncellemeBasari {
            get {
                return ResourceManager.GetString("GuncellemeBasari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenleme İşlemi Başarısız Olmuştur.
        /// </summary>
        internal static string GuncellemeBasarisiz {
            get {
                return ResourceManager.GetString("GuncellemeBasarisiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt İşlemi Başarılı Olmuştur.
        /// </summary>
        internal static string KayitBasari {
            get {
                return ResourceManager.GetString("KayitBasari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekleme İşlemi Başarısız Olmuştur.
        /// </summary>
        internal static string KayitBasarisiz {
            get {
                return ResourceManager.GetString("KayitBasarisiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Verinin İçeriğinde Bir Değişiklik Yapılmamıştır. Güncelleme Yapabilmek için En Az Bir Veriyi Değiştirmelisiniz.
        /// </summary>
        internal static string NotModifiedDataOnDatabaseException {
            get {
                return ResourceManager.GetString("NotModifiedDataOnDatabaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Veri Tabanında Bulunamamıştır.
        /// </summary>
        internal static string NullDataOnDatabaseCustomException {
            get {
                return ResourceManager.GetString("NullDataOnDatabaseCustomException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Veri Tipi Boş Değer Göndermiştir.
        /// </summary>
        internal static string NullReferenceException {
            get {
                return ResourceManager.GetString("NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirtilen yol, dosya adı veya her ikisi de çok uzun. Tam dosya adı uzunluğunun 260 karakterden ve dizin adının 248 karakterden az olması gerekir..
        /// </summary>
        internal static string PathTooLongException {
            get {
                return ResourceManager.GetString("PathTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme işlemi Başarılı Olmuştur.
        /// </summary>
        internal static string SilmeBasari {
            get {
                return ResourceManager.GetString("SilmeBasari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaldırma İşlemi Başarısız Olmuştur.
        /// </summary>
        internal static string SilmeBasarisiz {
            get {
                return ResourceManager.GetString("SilmeBasarisiz", resourceCulture);
            }
        }
    }
}
