//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QtekBilisim_Muhasebe.BL.Entity.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankaKayit
    {
        public int BankaID { get; set; }
        public int BankaBilgiID { get; set; }
        public int KrediKartID { get; set; }
        public int PosID { get; set; }
        public int CekID { get; set; }
        public int SenetID { get; set; }
        public string BankaAd { get; set; }
        public string HesapTur { get; set; }
        public string SubeKod { get; set; }
        public string HesapNumara { get; set; }
        public string IBAN { get; set; }
        public bool AktifMi { get; set; }
        public bool SilindiMi { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public System.DateTime GuncellemeTarih { get; set; }
        public int DilID { get; set; }
        public int SirketID { get; set; }
    }
}
