//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QtekBilisim_Muhasebe.BL.Entity.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankaHareket
    {
        public int BankaHareketID { get; set; }
        public int BankaID { get; set; }
        public string OzelKod { get; set; }
        public string EvrakNo { get; set; }
        public string IslemTur { get; set; }
        public int Vade { get; set; }
        public System.DateTime IslemTarih { get; set; }
        public System.TimeSpan IslemSaat { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> TutarBorc { get; set; }
        public Nullable<decimal> TutarAlacak { get; set; }
        public bool AktifMi { get; set; }
        public bool SilindiMi { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public System.DateTime GuncellemeTarih { get; set; }
        public int DilID { get; set; }
        public int SirketID { get; set; }
    }
}
