//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QtekBilisim_Muhasebe.BL.Entity.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariKayit
    {
        public int CariID { get; set; }
        public int IlceID { get; set; }
        public int DovizBirimID { get; set; }
        public string CariKod { get; set; }
        public string TicariUnvan { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string CepTelefon { get; set; }
        public string Faks { get; set; }
        public string VergiDaire { get; set; }
        public string VergiNo { get; set; }
        public string TC { get; set; }
        public string OzelKod_1 { get; set; }
        public string OzelKod_2 { get; set; }
        public string OzelKod_3 { get; set; }
        public string Resim { get; set; }
        public int Iskonto { get; set; }
        public int KullanilacakStokFiyat { get; set; }
        public int Vade { get; set; }
        public string KaraListe { get; set; }
        public string Not { get; set; }
        public bool DovizHesabiVarMi { get; set; }
        public string Yetkili { get; set; }
        public bool AktifMi { get; set; }
        public bool SilindiMi { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public System.DateTime GuncellemeTarih { get; set; }
        public int DilID { get; set; }
        public int SirketID { get; set; }
        public int KullaniciID { get; set; }
    }
}
