//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QtekBilisim_Muhasebe.BL.Entity.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaBilgi
    {
        public int FaturaID { get; set; }
        public string FaturaNumara { get; set; }
        public Nullable<System.DateTime> FaturaTarih { get; set; }
        public Nullable<System.TimeSpan> FaturaSaat { get; set; }
        public string CariBilgiler { get; set; }
        public string Grup { get; set; }
        public string OzelKod { get; set; }
        public string StokBilgiler { get; set; }
        public string KDV { get; set; }
        public Nullable<int> Iskonto { get; set; }
        public string EkBilgiler { get; set; }
        public bool AktifMi { get; set; }
        public bool SilindiMi { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public System.DateTime GuncellemeTarih { get; set; }
        public int DilID { get; set; }
        public int SirketID { get; set; }
    }
}
