//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QtekBilisim_Muhasebe.BL.Entity.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QtekBilisim_MuhasebeContext : DbContext
    {
        public QtekBilisim_MuhasebeContext()
            : base("name=QtekBilisim_MuhasebeContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdetBirim> AdetBirim { get; set; }
        public virtual DbSet<AlisFiyat> AlisFiyat { get; set; }
        public virtual DbSet<BankaBilgi> BankaBilgi { get; set; }
        public virtual DbSet<BankaHareket> BankaHareket { get; set; }
        public virtual DbSet<BankaKayit> BankaKayit { get; set; }
        public virtual DbSet<BorcBakiye> BorcBakiye { get; set; }
        public virtual DbSet<CariHareket> CariHareket { get; set; }
        public virtual DbSet<CariKayit> CariKayit { get; set; }
        public virtual DbSet<Cek> Cek { get; set; }
        public virtual DbSet<DepoKayit> DepoKayit { get; set; }
        public virtual DbSet<Dil> Dil { get; set; }
        public virtual DbSet<Dosya> Dosya { get; set; }
        public virtual DbSet<DovizBirim> DovizBirim { get; set; }
        public virtual DbSet<FaturaBilgi> FaturaBilgi { get; set; }
        public virtual DbSet<Grup> Grup { get; set; }
        public virtual DbSet<HareketSecim> HareketSecim { get; set; }
        public virtual DbSet<HataKayit> HataKayit { get; set; }
        public virtual DbSet<Ilce> Ilce { get; set; }
        public virtual DbSet<KasaHareket> KasaHareket { get; set; }
        public virtual DbSet<KasaKayit> KasaKayit { get; set; }
        public virtual DbSet<KdvOran> KdvOran { get; set; }
        public virtual DbSet<KrediKart> KrediKart { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Pos> Pos { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<SatisFiyat> SatisFiyat { get; set; }
        public virtual DbSet<Sehir> Sehir { get; set; }
        public virtual DbSet<Senet> Senet { get; set; }
        public virtual DbSet<SirketKayit> SirketKayit { get; set; }
        public virtual DbSet<SirketTur> SirketTur { get; set; }
        public virtual DbSet<StackTraceFrame> StackTraceFrame { get; set; }
        public virtual DbSet<StokBakiyeUyari> StokBakiyeUyari { get; set; }
        public virtual DbSet<StokHareket> StokHareket { get; set; }
        public virtual DbSet<StokKayit> StokKayit { get; set; }
        public virtual DbSet<TedarikciBilgi> TedarikciBilgi { get; set; }
        public virtual DbSet<Ulke> Ulke { get; set; }
        public virtual DbSet<Yetki> Yetki { get; set; }
        public virtual DbSet<YetkiAlan> YetkiAlan { get; set; }
        public virtual DbSet<YetkiDetay> YetkiDetay { get; set; }
        public virtual DbSet<AlacakBakiye> AlacakBakiye { get; set; }
    }
}
