//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QtekBilisim_Muhasebe.BL.Entity.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SirketKayit
    {
        public int SirketID { get; set; }
        public int SirketTurID { get; set; }
        public string TicariUnvan { get; set; }
        public string Yetkili { get; set; }
        public string VergiDaire { get; set; }
        public string VergiNumara { get; set; }
        public string VergiDaireKod { get; set; }
        public string TicariSicilNumara { get; set; }
        public string Adres { get; set; }
        public int IlceID { get; set; }
        public int CalismaYil { get; set; }
        public System.DateTime KurulusTarih { get; set; }
        public string Telefon_1 { get; set; }
        public string Telefon_2 { get; set; }
        public string Faks { get; set; }
        public string Muhasebeci { get; set; }
        public string Not { get; set; }
        public bool AktifMi { get; set; }
        public bool SilindiMi { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public int DilID { get; set; }
        public System.DateTime GuncellemeTarih { get; set; }
    }
}
