//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QtekBilisim_Muhasebe.BL.Entity.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKayit
    {
        public int StokID { get; set; }
        public int AdetBirimID { get; set; }
        public int StokBakiyeUyariID { get; set; }
        public int TedarikciID { get; set; }
        public string Durum { get; set; }
        public string StokAd { get; set; }
        public string BarkodNumara { get; set; }
        public string OzelKod_1 { get; set; }
        public string OzelKod_2 { get; set; }
        public string OTV { get; set; }
        public string OIV { get; set; }
        public string Aciklama { get; set; }
        public int KdvOranAlis { get; set; }
        public int KdvOranSatisParekende { get; set; }
        public int KdvOranSatisToptan { get; set; }
        public string TevkifatOran { get; set; }
        public string Resim { get; set; }
        public string DosyaEvrak { get; set; }
        public Nullable<decimal> AlisFiyat { get; set; }
        public Nullable<decimal> SatisFiyat { get; set; }
        public bool AktifMi { get; set; }
        public bool SilindiMi { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public System.DateTime GuncellemeTarih { get; set; }
        public int DilID { get; set; }
        public int SirketID { get; set; }
    }
}
